version: '3'

services:
  nginx:
    image: nginx:stable
    container_name: admin-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql


  mysql:
    image: mysql:8.0
    container_name: rcf-mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: larabbit_phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - 127.0.0.1:84:80
    volumes:
      - /sessions
    links:
      - mysql


  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: admin-php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

  admin-redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  admin-rabbitmq:
    image: rabbitmq:3.11-management
    container_name: admin-rabbitmq
    restart: unless-stopped
    volumes:
      - ./docker/rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

networks:
  default:
    name: "mm-network"
    external: true